version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Build & Deploy"
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker build -t toshkooshopov/devops_task_nexo:latest .
            docker push toshkooshopov/devops_task_nexo:latest

workflows:
  build_and_test:
    jobs:
      - build