version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: "Build & Deploy"
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker build -t toshkooshopov/devops_task_nexo:${CIRCLE_SHA1} .
            docker push toshkooshopov/devops_task_nexo:${CIRCLE_SHA1}
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test